configuration:
  - Debug

environment:
  matrix:
    - platform: Win64
      language: cpp
      image: Visual Studio 2019

test: off

install:
  - git submodule update --init --recursive

before_build:
  - if %platform%==Win64 set vcplatform=x64

build_script:
  - mkdir build_msvc
  - cd build_msvc
  - cmake -G "Visual Studio 16 2019" ../
  - msbuild concol.sln /p:Platform=%vcplatform%
  - cd test
  - msbuild test_concol.sln /p:Platform=%vcplatform%